config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :albums do 
        resources :artists do
          resources :tracks
        end
        resources :tracks
      end
      resources :artists do
        resources :albums do 
          resources :tracks
        end
        resources :tracks
      end
    end
  end
  resources :artists do
    resources :albums
  end
  root 'artists#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
	has_and_belongs_to_many :tracks
	belongs_to :artist
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums, dependent: :destroy
	has_many :track, dependent: :destroy
end

app/models/track.rb
class Track < ActiveRecord::Base
	has_and_belongs_to_many :albums
	belongs_to :artist
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    artist = params[:artist_id] ? 'artists/' + params[:artist_id] + '/' : ''
    response = RestClient.get @api_url + artist + 'albums?with=artist'
    response = JSON.parse(response)
    @albums = response["data"]
  end

  def create
    #logger.info "_____________________________________: " + pa.inspect
    response = RestClient.post @api_url + "albums", album_params.to_json, :content_type => :json, :accept => :json
    response = JSON.parse(response)
    @album = response['data']
    logger.debug "@album : " + @album.inspect
    if(response["meta"]["code"] == 201) 
      params[:tracks].each do |track|
        track["artist_id"] = @album["artist_id"]
        response2 = RestClient.post @api_url + "albums/" + @album["id"].to_s + "/tracks", track.to_json, :content_type => :json, :accept => :json
      end      
    end
    
    redirect_to artist_album_path(@album['artist_id'], @album['id'])
    
  end

  def update
    @artist = Artist.find(params[:id])

    @artist.update_attributes(write_params)

    generic_response @artist
  end

  def new
    response = RestClient.get @api_url + 'artists'
    response = JSON.parse(response)
    @artists = response['data']

    response = RestClient.get @api_url + 'artists/' + params[:artist_id]
    response = JSON.parse(response)
    @artist = response['data'][0]
  end


  def destroy
    @artist.destroy
    @response = {:data => [], :meta => {:code => 200}}
    respond_with @response
  end

  def show
    response = RestClient.get @api_url + 'albums/' + params[:id] + '?with=tracks,artist'
    response = JSON.parse(response)
    @album = response["data"][0]
  end

  private
  ## Strong Parameters 
  def album_params
    params.permit(:title, :year, :artist_id)
  end

  def track_params
    params.permit(:title, :artist_id)
  end

  def filter_params
    params.permit(:title, :id)
  end
end

app/controllers/api/v1/albums_controller.rb
module Api
  module V1
    class AlbumsController < ApiController
      def index
        @data = Album.where(filter_params).all
        generic_response @data
      end

      def create
        @album = Album.new(write_params)

        if @album.save
          generic_response @album, 201
        else
          generic_response [], 400
        end
      end

      def update
        @album = Album.find(params[:id])

        @album.update_attributes(write_params)

        generic_response @album
      end

      def new
      end


      def destroy
        @album = Album.find(params[:id])
        @album.destroy
        generic_response []
      end

      def show
        index
      end

      private
      ## Strong Parameters 
      def write_params
        params.permit(:title, :year, :artist_id)
      end

      def filter_params
        params.permit(:title, :id, :year, :artist_id)
      end
    end
  end
end

app/controllers/api/v1/artists_controller.rb
module Api
  module V1
    class ArtistsController < ApiController
      def index
        @data = Artist.where(filter_params).all
        generic_response @data
      end

      def create
        @artist = Artist.new(write_params)

        if @artist.save
          generic_response @artist, 201
        else
          generic_response [], 400
        end
      end

      def update
        @artist = Artist.find(params[:id])

        @artist.update_attributes(write_params)

        generic_response @artist
      end

      def new
      end


      def destroy
        @artist.destroy
        @response = {:data => [], :meta => {:code => 200}}
        respond_with @response
      end

      def show
        index
      end

      private
      ## Strong Parameters 
      def write_params
        params.permit(:title)
      end

      def filter_params
        params.permit(:title, :id)
      end
    end
  end
end

app/controllers/api/v1/tracks_controller.rb
module Api
  module V1
    class TracksController < ApiController
      def index
        @data = Track.where(filter_params).all
        generic_response @data
      end

      def create
        @track = Track.new(write_params)

        @album = Album.find(params[:album_id])

        @album.tracks << @track

        if @album.save
          generic_response @track, 201
        else
          generic_response [], 400
        end
      end

      def update
        @track = Track.find(params[:id])

        @track.update_attributes(write_params)

        generic_response @track
      end

      def new
      end


      def destroy
        @track = Track.find(params[:id])
        @track.destroy
        generic_response []
      end

      def show
        index
      end

      private
      ## Strong Parameters 
      def write_params
        params.permit(:title, :year, :artist_id)
      end

      def filter_params
        params.permit(:title, :id, :year, :artist_id)
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :null_session
  
  	respond_to :json
  	responders :json

  	rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  	def generic_response(data, status = 200)
        @response = {:data => data, :meta => {:code => status}}

        if params[:with]
        	#@response = @response.to_json(include: params[:with])
          @response = @response.to_json(include: params[:with].split(','))

        end
        
        respond_with(@response, :status => status,:location => nil)
    end

	def record_not_found
		render json: {
			meta: {
				code: 404,
				error_type: 'RecordError',
				error_message: 'Record Not Found'
			},
			data: []
		}, status: 404
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  def initialize()
  	super
  	@api_url = 'http://localhost:3002/api/v1/';	
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    response = RestClient.get @api_url + 'artists'
    response = JSON.parse(response)
    @artists = response["data"]
  end

  def create
    #logger.info "_____________________________________: " + pa.inspect
    response = RestClient.post @api_url + "artists", artist_params.to_json, :content_type => :json, :accept => :json
    response = JSON.parse(response)
    @artist = response['data']
    logger.debug "@artist : " + @artist.inspect

    redirect_to artists_path
  end

  def update
    @artist = Artist.find(params[:id])

    @artist.update_attributes(write_params)

    generic_response @artist
  end

  def new
    response = RestClient.get @api_url + 'artists'
    response = JSON.parse(response)
    @artists = response['data']
  end


  def destroy
    @artist.destroy
    @response = {:data => [], :meta => {:code => 200}}
    respond_with @response
  end

  def show
    response = RestClient.get @api_url + 'artists/' + params[:id] + '?with=albums'
    response = JSON.parse(response)
    @artist = response["data"][0]
  end

  private
  ## Strong Parameters 
  def artist_params
    params.permit(:title)
  end

  def filter_params
    params.permit(:title, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h1>Albums</h1>
<ul>
<% @albums.each do |album| %>
	<li><%= link_to "#{album['artist']['title']} - #{album['title']}(#{album['year']})", artist_album_path(album['artist']['id'], album['id']) %></li>
<% end %>
</ul>

app/views/albums/new.html.erb
<ol class="breadcrumb">
  <li><a href="/">Artists</a></li>
  <li><a href="/"><%= link_to @artist['title'], artist_path(@artist['id'].to_i) %></a></li>
  <li class="active">Create New Album</li>
</ol>

<%= form_tag('/albums') do %>
	<div class='col-md-6'>
		<h1>New Album</h1>
		<%= label_tag(:title, "Album Title:") %><br />
		<%= text_field_tag(:title, '', class: "form-control", id: "album_title") %><br />
		<%= label_tag(:artist_id, "Artist:") %><br />
		<select name="artist_id" id="artist_id" class='form-control'>
			<% logger.debug "paramswsasdfasdf :  " + params.inspect %>
			<% @artists.each do |artist| %>
				<option value="<%= artist['id'] %>" <%= params[:artist_id] == artist['id'].to_s ? 'selected' : '' %> ><%= artist['title'] %></option>
			<% end %>
		</select><br />
		<%= label_tag(:album_year, "Album Year:") %><br />
		<%= text_field_tag(:year, '', class: "form-control", id: "album_year") %><br />

		<br/>
		<%= submit_tag("Save", class: "btn btn-success") %>
	</div>
	<div class='col-md-6'>
		<h2>Fetched album Cover</h2>
		<img src="" id='fetched-cover' width="100" height="100" alt="" />
		<br><br>
		
		<h3>Tracklist</h3>	
		<div id="tracklist">
			
		</div>
	</div>
<% end %>

app/views/albums/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">Artists</a></li>
  <li><a href="/"><%= link_to @album['artist']['title'], artist_path(@album['artist']['id']) %></a></li>
  <li class="active"><%= @album['title'] %></li>
</ol>

<h1><%= "#{@album['artist']['title']} - #{@album['title']}" %></h1>
<ol>
	<% @album["tracks"].each do |track| %>
		<li><%= track["title"] %></li>
	<% end %>
</ol>

app/views/artists/index.html.erb
<ol class="breadcrumb">
  <li class="active">Home</li>
</ol>

<h1>Artists</h1>
<ul>
<% @artists.each do |artist| %>
	<li><%= link_to "#{artist['title']}", artist_path(artist['id']) %></li>
<% end %>
	<li>
		<div class='row'>
			<div class='col-md-6'>
				<%= form_tag('/artists') do %>
					<%= label_tag(:title, "Artist name:") %><br />
					<%= text_field_tag(:title, '', class: "form-control", id: "artist_title") %><br />
					<%= submit_tag("Add New", class: "btn btn-success") %>
				<% end %>
			</div>
		</div>
	</li>
</ul>

app/views/artists/new.html.erb
<%= form_tag('/albums') do %>
	<div class='col-md-6'>
		<h1>New Artist</h1>
		<%= label_tag(:title, "Artist name:") %><br />
		<%= text_field_tag(:title, '', class: "form-control", id: "artist_title") %><br />
		<br/>
		<%= submit_tag("Save", class: "btn btn-success") %>
	</div>
<% end %>

app/views/artists/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">Artists</a></li>
  <li class="active"><%= @artist['title'] %></li>
</ol>

<h1><%= @artist['title'] %></h1>
<h2>Albums <%= link_to "Add New", new_artist_album_path(@artist['id']), {class: 'btn btn-success btn-xs'} %></h2>
<ul>
	<% @artist['albums'].each do |album| %>
	<li><%= link_to "#{album['title']}(#{album['year']})", artist_album_path(@artist['id'], album['id']) %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simfy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' type='text/javascript'></script>
  <script src='/simfy.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Simfy Test</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
	<%= yield %>
</div>

</body>
</html>